TextFormat:
  MainChat: "[player]&a:&r [message]"
  PrivateChat: "[[sender] > [receiver]]&a&r [message]"
  Mail: "[[sender] > [receiver]]&a:&r [message]"
MessageFormat:
  Normal: "[original]"
  Converted: "[converted]&7([original]&7)"
DynmapServer: "main"
MailDays: 30