TextFormat:
  MainChat: "[server][player]&a:&r [message]"
  PrivateChat: "[[s_server][sender] > [r_server][receiver]]&a&r [message]"
  Mail: "[[sender] > [receiver]]&a:&r [message]"
  Broadcast: "[message]"
MessageFormat:
  Normal: "[original]"
  Converted: "[converted]&7([original]&7)"
Servers:
- "main:&b[M]"
DynmapServer: "main"
MailDays: 30
MailMessage: "&bメール受信メッセージ編集機能（[size]件のメールを受信しました。）\n/mail clearで削除できます。"
AntiSpam:
  Term: 5
  #Term秒間に、
  Limit: 4
  #Limit回より多く発言すると、
  PeriodOfTimeToMute: 10
  #PeriodOfTimeToMute分ミュートされる